import type { Metadata } from "next";

import NavBar from "./components/NavBar";
import QueryClientProvider from "./QueryClientProvider";
import AuthProvider from "./auth/Provider";

import { NextIntlClientProvider, useMessages } from "next-intl";
import { useTranslate } from "@/app/Translations";
import { Container, CssBaseline } from "@mui/material";
import { ColorModeProvider } from "./components/ColorModeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const translations = {
    links: [
      {
        label: useTranslate("components.navBar.links.dashboard"),
        href: "/dashboard",
        startLink: "/dashboard",
      },
      {
        label: useTranslate("components.navBar.links.students"),
        href: "/students/list",
        startLink: "/students",
      },
    ],
    action: useTranslate("components.navBar.action"),
    logout: useTranslate("components.navBar.logout"),
  };

  const messages = useMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ColorModeProvider>
            <QueryClientProvider>
              <CssBaseline />
              <AuthProvider>
                <NavBar translations={translations} />
                <Container>{children}</Container>
              </AuthProvider>
            </QueryClientProvider>
          </ColorModeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
